name: Terraform Plan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Select workspace
        run: |
          tf_workspace="${{ github.event.pull_request.number }}"
          terraform workspace select "$tf_workspace" || terraform workspace new "$tf_workspace"
      - name: Terraform Init
        run: terraform init -backend-config="key=state/feature/${{ github.event.pull_request.number }}.tfstate"
      - name: Terraform Plan
        run: terraform plan -var="environment=feature-${{ github.event.pull_request.number }}"
