name: Terraform Destroy

on:
  pull_request:
    types: [closed]

jobs:
  destroy:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Select workspace
        run: terraform workspace select "${{ github.event.pull_request.number }}"
      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="environment=feature-${{ github.event.pull_request.number }}"
      - name: Delete workspace
        run: terraform workspace delete "${{ github.event.pull_request.number }}"
